server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onthetop?user=root=true&serverTimezone=UTC&useSSL=true&verifyServerCertificate=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-on-migrate: true